name: CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show current directory
        run: ls

      - name: Установка зависимостей
        run: npm run init

      - name: Starting ESlint
        run: npm run lint

      - name: Starting Prettier
        run: npm run prettier

      - name: Build Next.js app
        run: npm run build