name: CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Show current directory
        run: echo $PWD

      - name: Установка зависимостей
        run: npm run init
        working-directory: ../

      - name: Starting ESlint
        run: npm run lint

      - name: Starting Prettier
        run: npm run prettier

      - name: Build Next.js app
        run: npm run build